##### Импортируем NumPy

In [1]:
import numpy as np

##### Примеры создания массивов

In [2]:
# обычный список
l = np.array([10, 20, 30, 40])
print("Массив из списка:", l)

# нули
z = np.zeros((2, 3))
print("Массив из нулей:\n", z)

# единицы
e = np.ones((3, 2))
print("Массив из единиц:\n", e)

#  числа от 0 до 9
r = np.arange(0, 10)
print("Массив с числами от 0 до 9:", r)

Массив из списка: [10 20 30 40]
Массив из нулей:
 [[0. 0. 0.]
 [0. 0. 0.]]
Массив из единиц:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Массив с числами от 0 до 9: [0 1 2 3 4 5 6 7 8 9]


#### Демонстрация атрибутов

In [6]:
b = 12 * np.transpose(e)
print("Форма массива из нулей:", z.shape)
print("Тип данных массива чисел от 0 до 9:", r.dtype)
print("Форма и тип данных массива b:", b.shape, b.dtype)

Форма массива из нулей: (2, 3)
Тип данных массива чисел от 0 до 9: int64
Форма и тип данных массива b: (2, 3) float64


#### Индексирование и срезы

In [8]:
# вывод отдельного элемента/ов
print("2-ой элемент массива из списка:", l[1])
print("Последние 3 элемента:", r[-3:])
print("Каждый второй элемент:", r[::2])
# срез
print("Элементы с 3 по 6:", r[3:7])

# поиграемся с двумерным массивом
matr = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("\nЭлемент из 3-й строки и 2-го столбца:", matr[2, 1])
print("Срез первой строки:", matr[0, :])
print("Срез второго столбца:", matr[:, 1])


2-ой элемент массива из списка: 20
Последние 3 элемента: [7 8 9]
Каждый второй элемент: [0 2 4 6 8]
Элементы с 3 по 6: [3 4 5 6]

Элемент из 3-й строки и 2-го столбца: 8
Срез первой строки: [1 2 3]
Срез второго столбца: [2 5 8]


#### Векторные операции и статистики

In [10]:
# поэлементное сложение/умножение
sum_ar = l + np.array([1, 2, 3, 4])
mul_ar = l * 5
print("Поэлементное сложение:", sum_ar)
print("Поэлементное умножение:", mul_ar)

# вычисление средней величины/суммы всех элементов
mean_znach = r.mean()
tot = b.sum()
print("\nСреднее значение массива из чисел:", mean_znach)
print("Сумма всех элементов массива b:", tot)

# стандартное отклонение, max и min
std_val = b.std()
print("Стандартное отклонение массива b:", std_val)
print("Максимум:", r.max())
print("Минимум:", r.min())

# поэлементное сравнение
com = l > 10
print("\nЭлементы больше 10:", com)

Поэлементное сложение: [11 22 33 44]
Поэлементное умножение: [ 50 100 150 200]

Среднее значение массива из чисел: 4.5
Сумма всех элементов массива b: 72.0
Стандартное отклонение массива b: 0.0
Максимум: 9
Минимум: 0

Элементы больше 10: [False  True  True  True]
